export const PATH_INICIAL = '/'
export const PATH_NOT_FOUND = '*'
export const PATH_LOGIN = '/login'
export const PATH_MAIN = '/home'
export const PATH_REGISTER_CLIENT = '/register_client'
export const PATH_CONSULT_CLIENT = '/consult_client'
