import { useEffect, useState } from 'react'
import { Form, InputNumber, Modal, Select, Table, Divider, Typography, Row, Col, Input, Button, Tooltip, Space, Alert } from 'antd'
import { CheckOutlined } from '@ant-design/icons'
import { useCustomMutation } from '../../../hooks/UseCustomMutation'
import ventaService from '../services/ventaService'
import { showNotification } from '../../../utils/showNotification'
import { showHandleError } from '../../../utils/handleError'
import type { CreatePagoDto, VentaDto, PagoDistribucionDto } from '../dto-ventaDto'

const { Option } = Select
const { Text } = Typography

interface PagoFormProps {
  visible: boolean
  onCancel: () => void
  onSuccess: () => void
  idVenta: number
  saldoPendiente: number
}

const PagoForm = ({
  visible,
  onCancel,
  onSuccess,
  idVenta,
}: PagoFormProps) => {
  const [form] = Form.useForm()
  const montoTotalForm = Form.useWatch('monto_total', form)
  const [venta, setVenta] = useState<VentaDto | null>(null)
  const [loading, setLoading] = useState(false)
  
  // Local state for distribution to avoid complex Form.Item nested paths
  const [distCuotas, setDistCuotas] = useState<Record<number, { monto: number, monto_mora: number }>>({})
  const [distCargos, setDistCargos] = useState<Record<number, number>>({})

  const { mutate: fetchVenta } = useCustomMutation({
    execute: ventaService.getVentaById,
    onSuccess: (res) => {
      setVenta(res.data)
      const initialCuotas: Record<number, { monto: number, monto_mora: number }> = {}
      res.data.cuotas?.forEach(c => {
        initialCuotas[c.id] = { monto: 0, monto_mora: 0 }
      })
      setDistCuotas(initialCuotas)

      const initialCargos: Record<number, number> = {}
      res.data.cargos?.forEach(c => {
        initialCargos[c.id] = 0
      })
      setDistCargos(initialCargos)
    },
    onError: (e) => showHandleError(e as never),
  })

  const { mutate: createPago, isPending: isSubmitting } = useCustomMutation({
    execute: ventaService.createPago,
    onSuccess: () => {
      showNotification({
        type: 'success',
        message: 'Pago registrado correctamente',
      })
      form.resetFields()
      setDistCuotas({})
      setDistCargos({})
      onSuccess()
    },
    onError: (e) => showHandleError(e as never),
  })

  useEffect(() => {
    if (visible && idVenta) {
      setLoading(true)
      fetchVenta(idVenta)
      setLoading(false)
    }
  }, [visible, idVenta, fetchVenta])

  const [lastAutoGeneratedDesc, setLastAutoGeneratedDesc] = useState('')

  useEffect(() => {
    if (!venta) return

    const parts: string[] = []
    
    const cuotasPagadas = Object.entries(distCuotas)
      .filter(([_, data]) => data.monto > 0)
      .map(([id]) => venta.cuotas?.find(c => c.id === Number(id))?.numero_cuota)
      .filter(Boolean)
    if (cuotasPagadas.length > 0) parts.push(`Cuotas: ${cuotasPagadas.join(', ')}`)

    const morasPagadas = Object.entries(distCuotas)
      .filter(([_, data]) => data.monto_mora > 0)
      .map(([id]) => venta.cuotas?.find(c => c.id === Number(id))?.numero_cuota)
      .filter(Boolean)
    if (morasPagadas.length > 0) parts.push(`Moras: ${morasPagadas.join(', ')}`)

    const cargosPagados = Object.entries(distCargos)
      .filter(([_, monto]) => monto > 0)
      .map(([id]) => venta.cargos?.find(c => c.id === Number(id))?.nombre)
      .filter(Boolean)
    if (cargosPagados.length > 0) parts.push(`Cargos: ${cargosPagados.join(', ')}`)

    const newDesc = parts.join('. ')
    const currentDesc = form.getFieldValue('descripcion') || ''

    // Only update if current is empty or matches previous auto-gen
    if (currentDesc === lastAutoGeneratedDesc) {
      form.setFieldsValue({ descripcion: newDesc })
      setLastAutoGeneratedDesc(newDesc)
    }
  }, [distCuotas, distCargos, venta, form, lastAutoGeneratedDesc])

  const totalDistribuido = 
    Object.values(distCuotas).reduce((acc, curr) => acc + curr.monto + curr.monto_mora, 0) +
    Object.values(distCargos).reduce((acc, curr) => acc + curr, 0)

  const saldoFaltanteporD = (montoTotalForm || 0) - totalDistribuido

  const onFinish = (values: any) => {
    const totalPagar = values.monto_total || 0
    if (totalDistribuido !== totalPagar) {
      showNotification({
        type: 'error',
        title: 'Validación de monto',
        message: `El total distribuido ($${totalDistribuido.toLocaleString()}) debe ser igual al monto a pagar ($${totalPagar.toLocaleString()})`
      })
      return
    }

    const distribucion: PagoDistribucionDto[] = []

    Object.entries(distCuotas).forEach(([id, data]) => {
      if (data.monto > 0 || data.monto_mora > 0) {
        distribucion.push({
          tipo: 'CUOTA',
          id_referencia: Number(id),
          monto: data.monto,
          monto_mora: data.monto_mora
        })
      }
    })

    Object.entries(distCargos).forEach(([id, monto]) => {
      if (monto > 0) {
        distribucion.push({
          tipo: 'CARGO',
          id_referencia: Number(id),
          monto
        })
      }
    })

    const payload: CreatePagoDto = {
      id_venta: idVenta,
      monto_total: totalPagar,
      metodo_pago: values.metodo_pago,
      descripcion: values.descripcion,
      distribucion
    }
    createPago(payload)
  }

  const handleCuotaChange = (id: number, field: 'monto' | 'monto_mora', value: number | null) => {
    setDistCuotas(prev => ({
      ...prev,
      [id]: { ...prev[id], [field]: value || 0 }
    }))
  }

  const handleCargoChange = (id: number, value: number | null) => {
    setDistCargos(prev => ({
      ...prev,
      [id]: value || 0
    }))
  }

  const fillRemaining = (id: number, type: 'CUOTA_CAPITAL' | 'CUOTA_MORA' | 'CARGO', pending: number) => {
    const disponible = saldoFaltanteporD
    
    if (disponible <= 0) return

    const aPagar = Math.min(pending, disponible)

    if (type === 'CUOTA_CAPITAL') {
      handleCuotaChange(id, 'monto', (distCuotas[id]?.monto || 0) + aPagar)
    } else if (type === 'CUOTA_MORA') {
      handleCuotaChange(id, 'monto_mora', (distCuotas[id]?.monto_mora || 0) + aPagar)
    } else if (type === 'CARGO') {
      handleCargoChange(id, (distCargos[id] || 0) + aPagar)
    }
  }

  return (
    <Modal
      title="Registrar Pago con Distribución Manual"
      open={visible}
      onCancel={onCancel}
      onOk={() => form.submit()}
      confirmLoading={isSubmitting}
      okText="Registrar"
      cancelText="Cancelar"
      width={1000}
      okButtonProps={{ disabled: saldoFaltanteporD !== 0 || (montoTotalForm || 0) <= 0 }}
    >
      <Form
        form={form}
        layout="vertical"
        onFinish={onFinish}
        initialValues={{ metodo_pago: 'EFECTIVO' }}
      >
        <Divider orientation="left">1. Información General</Divider>
        <Row gutter={16}>
          <Col span={8}>
            <Form.Item
              name="monto_total"
              label="Monto Total a Pagar"
              rules={[{ required: true, message: 'Ingrese el monto' }]}
            >
              <InputNumber
                style={{ width: '100%' }}
                min={1}
                formatter={(value) => `$ ${value}`.replace(/\B(?=(\d{3})+(?!\d))/g, ',')}
                parser={(value) => value!.replace(/\$\s?|(,*)/g, '') as any}
              />
            </Form.Item>
          </Col>
          <Col span={8}>
            <Form.Item name="metodo_pago" label="Método de Pago">
              <Select>
                <Option value="EFECTIVO">EFECTIVO</Option>
                <Option value="TRANSFERENCIA">TRANSFERENCIA</Option>
                <Option value="CHEQUE">CHEQUE</Option>
                <Option value="TARJETA">TARJETA</Option>
              </Select>
            </Form.Item>
          </Col>
          <Col span={8}>
            <Form.Item name="descripcion" label="Descripción / Comentario">
              <Input placeholder="Ej. Pago cuota marzo" />
            </Form.Item>
          </Col>
        </Row>

        <Divider orientation="left">2. Aplicar a Cuotas</Divider>
        <Table
          loading={loading}
          dataSource={venta?.cuotas?.filter(c => c.estado !== 'PAGADA') || []}
          rowKey="id"
          pagination={false}
          size="small"
          columns={[
            { title: 'Cuota', dataIndex: 'numero_cuota' },
            { title: 'Vencimiento', dataIndex: 'fecha_vencimiento', render: (d) => d?.split('T')[0] },
            { 
              title: 'Pendiente', 
              render: (_, record) => {
                const total = record.monto_cuota || record.monto || 0
                const pagado = record.monto_pagado || 0
                return `$${(total - pagado).toLocaleString()}`
              }
            },
            { 
              title: 'Mora Calc.', 
              dataIndex: 'mora_calculada', 
              render: (v) => <Text type="danger">${(v || 0).toLocaleString()}</Text> 
            },
            {
              title: 'Pagar Capital',
              width: 180,
              render: (_, record) => {
                const pendiente = (record.monto_cuota || record.monto || 0) - (record.monto_pagado || 0)
                const actual = distCuotas[record.id]?.monto || 0
                const porPagar = pendiente - actual
                const disponibleOverall = saldoFaltanteporD

                return (
                  <Space.Compact style={{ width: '100%' }}>
                    <InputNumber
                      min={0}
                      max={pendiente}
                      value={actual}
                      onChange={(val) => handleCuotaChange(record.id, 'monto', val)}
                      style={{ width: '100%' }}
                    />
                    <Tooltip title="Saldar con saldo disponible">
                      <Button 
                        icon={<CheckOutlined />} 
                        onClick={() => fillRemaining(record.id, 'CUOTA_CAPITAL', porPagar)}
                        disabled={disponibleOverall <= 0 || porPagar <= 0}
                      />
                    </Tooltip>
                  </Space.Compact>
                )
              }
            },
            {
              title: 'Pagar Mora',
              width: 180,
              render: (_, record) => {
                const pendiente = record.mora_calculada || 0
                const actual = distCuotas[record.id]?.monto_mora || 0
                const porPagar = pendiente - actual
                const disponibleOverall = saldoFaltanteporD

                return (
                  <Space.Compact style={{ width: '100%' }}>
                    <InputNumber
                      min={0}
                      max={pendiente}
                      value={actual}
                      onChange={(val) => handleCuotaChange(record.id, 'monto_mora', val)}
                      style={{ width: '100%' }}
                    />
                    <Tooltip title="Pagar mora con saldo disponible">
                      <Button 
                        icon={<CheckOutlined />} 
                        onClick={() => fillRemaining(record.id, 'CUOTA_MORA', porPagar)}
                        disabled={disponibleOverall <= 0 || porPagar <= 0}
                      />
                    </Tooltip>
                  </Space.Compact>
                )
              }
            }
          ]}
        />

        <Divider orientation="left">3. Aplicar a Cargos</Divider>
        <Table
          loading={loading}
          dataSource={venta?.cargos?.filter(c => c.saldo_pendiente > 0) || []}
          rowKey="id"
          pagination={false}
          size="small"
          columns={[
            { title: 'Cargo', dataIndex: 'nombre' },
            { title: 'Pendiente', dataIndex: 'saldo_pendiente', render: (v) => `$${v.toLocaleString()}` },
            {
              title: 'Monto a Pagar',
              width: 200,
              render: (_, record) => {
                const pendiente = record.saldo_pendiente || 0
                const actual = distCargos[record.id] || 0
                const porPagar = pendiente - actual
                const disponibleOverall = saldoFaltanteporD

                return (
                  <Space.Compact style={{ width: '100%' }}>
                    <InputNumber
                      min={0}
                      max={pendiente}
                      value={actual}
                      onChange={(val) => handleCargoChange(record.id, val)}
                      style={{ width: '100%' }}
                    />
                    <Tooltip title="Saldar cargo con saldo disponible">
                      <Button 
                        icon={<CheckOutlined />} 
                        onClick={() => fillRemaining(record.id, 'CARGO', porPagar)}
                        disabled={disponibleOverall <= 0 || porPagar <= 0}
                      />
                    </Tooltip>
                  </Space.Compact>
                )
              }
            }
          ]}
        />

        <div style={{ marginTop: 24, padding: '16px', background: '#f5f5f5', borderRadius: '8px' }}>
          <Row justify="space-between" align="middle" gutter={16}>
            <Col>
              <Text style={{ fontSize: 16 }}>
                Monto a Pagar: <Text strong>${(montoTotalForm || 0).toLocaleString()}</Text>
              </Text>
            </Col>
            <Col>
              <Text style={{ fontSize: 16 }}>
                Saldo por Distribuir: <Text strong style={{ color: saldoFaltanteporD === 0 ? '#52c41a' : '#faad14' }}>
                  ${saldoFaltanteporD.toLocaleString()}
                </Text>
              </Text>
            </Col>
            <Col>
              <Text style={{ fontSize: 16 }}>
                Total Distribuido: <Text strong style={{ color: totalDistribuido === (montoTotalForm || 0) && (montoTotalForm || 0) > 0 ? '#52c41a' : '#ff4d4f' }}>
                  ${totalDistribuido.toLocaleString()}
                </Text>
              </Text>
            </Col>
          </Row>
          {saldoFaltanteporD !== 0 && (montoTotalForm || 0) > 0 && (
            <Alert
              type="warning"
              message={`Distribución incompleta: faltan $${saldoFaltanteporD.toLocaleString()} por asignar.`}
              style={{ marginTop: 12 }}
              showIcon
            />
          )}
        </div>
      </Form>
    </Modal>
  )
}

export default PagoForm
